# You can set multiple versions of node here
language: node_js
node_js:
  - 11.6.0

# This tells Travis to cache the node_modules files
cache: npm

# Travis lifecycle methods
install:
  - npm install
script:
  - npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: $EB_APP
  env: $EB_ENV
  bucket_name: $BUCKET_NAME
